load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "IOUtil",
    srcs = ["IOUtil.java"],
    main_class = "src/com/thrillio/utils/IOUtil.java",
    visibility = ["//src/com/thrillio/controllers:__pkg__","//src/com/thrillio:__pkg__"],
)
